### ISSUE TITLE
能做成前后端分离的吗？

### ISSUE THREAD

**Issue by ohyeah521** [1251240000/StockVisualization#5]
能做成前后端分离的吗？

**Comment by 1251240000** [comment]
完全可以，这个项目也是我在学习Django的过程中实现的，各方面都有许多缺陷，如有需要完全可以依照Restful API规范重构。

**Comment by ohyeah521** [comment]
> ，如有需要完

 我最近也在研究股票，用django实现要求写代码的人前后端都得懂，不利于后期维护，我打算根据自选股中的股票去抓取行业相关的新闻，然后展示在个股的明细信息下面。

**Comment by 1251240000** [comment]
我在开发时也想过为不同股票爬取其相关的新闻讯息，Tushare pro 接口会提供部分的新闻公告接口，但接口使用有积分限制，遂放弃。如果要抓取行业相关的新闻可以抓取到新闻后进行分类，再根据股票类型展示出不同的新闻。

**Comment by ohyeah521** [comment]
可以爬雪球，东方财富的相关新闻，然后整理入库，即可。
加个微信：hibandit
